### ISSUE TITLE
How to run it for our own dataset ?

### ISSUE THREAD

**Issue by manansaxena** [deepmind/Temporal-3D-Pose-Kinetics#1]
Hi,
I loved the work you have done and its quite interesting.
I had two doubts - 
1)How to run it for our own dataset containing videos.
2)How to extract the final 3D-joint locations(after the bundle adjustments)?

**Comment by cdoersch** [comment]
Unfortunately, we are currently unable to release our original implementation due to its reliance on internal tools.  

We include 3D keypoint locations in our released file (`3d_keypoints`).  If you're re-implementing the algorithm, you will need to use the SMPL model to compute the 3D mesh vertices from the pose and shape vectors, and then regress to 3D keypoints using the supplied regression matrix.  This joint regressor is implemented in the hmr codebase. See: https://github.com/akanazawa/hmr/blob/master/src/tf_smpl/batch_smpl.py

**Comment by manansaxena** [comment]
Thanks a lot for the help.
